### PR TITLE
Improve French translation

### PR DESCRIPTION
**Pull request by xinxinxinxinxin**

### CODE REVIEW

**Comment by Poussinou** [comment]
Merci de tes améliorations sur ce que j'avais fait, c'est cool :)
Par contre faut faire attention à certaines traductions, trop longues, qui peuvent dépasser du cadre d'un bouton par exemple... Mais c'est cool :)

**Comment by czlowiekimadlo** [comment]
Sorry guys, we don't speak french xD
@Poussinou since you have contributed our French files, is this good to merge? :D

**Review by Poussinou — APPROVED** [review]

**Comment by Poussinou** [comment]
Yes, this PR is good to merge, it corrects some mistakes I did earlier :+1: 
Maybe some translations are a little bit to long to fit the size of the buttons in the game, but I don't think this happens here, so you can merge ^^

**Comment by czlowiekimadlo** [comment]
Thanks for your contributions @xinxinxinxinxin and @Poussinou :D

**Pull request merged**
