### PR TITLE
french translation

### PR DESCRIPTION
**Pull request by Poussinou**
Does it works for you?

I really need more space to display the label "join" in french, please^^

### CODE REVIEW

**Comment by czlowiekimadlo** [comment]
I will check this today after work. Fitting labels in limited spaces is always a challange. I'm afraid we will not change the size of buttons just for this - we either have to get creative, or accept, that label overflows a bit. In Polish we had to shorten certain words just to make them fit.

Overall, if it overflows only a bit, it is not a big issue for us, and we will accept it ;)

**Comment by czlowiekimadlo** [comment]
I have added few new translations yesterday, so Github complains about conflict. Could you rebase your changes with latest master?

Also, using interactive rebase to merge all three commits into one, so only one is included in PR makes it easier to review ;)

**Comment by Poussinou** [comment]
Yep, to fit the different words in French can be very difficult too ^^
No time to check the new translations, I'll do it this weekend;)

**Comment by Poussinou** [comment]
What's interactive rebase? Sorry for the different commits in only one pull request, but it's difficult to translate well the first time, and sometimes I do some changes so that the translation will be better after them :-)

**Comment by czlowiekimadlo** [comment]
Weekend is fine, my plan is to release on Friday next week. As for rebase, here is a decent article about that:
http://ndlib.github.io/practices/one-commit-per-pull-request/

Also, if you are using cmd tools, have already made a commit, and now want to add more to it (it has to be on top of history), then:
- do your changes in files
- git add
- instead of 'git commit -m message' you can do 'git commit --amend'

This will allow you to add more things to already existing commit. Please be aware, that, if you already pushed that commit to your remote repository on github, you will have to do 'git push --force' to overwrite the remote repository history. Generally, this is a bad idea, but since you, most likely, work alone on your fork, it will be ok.
When you have three commits in your remote repository already, just checkout your master branch, do 'git merge -i HEAD~3', change words in top lines from:
pick
pick
pick
to:
pick
squash
squash

After you exit the editor, you will get another one, where you will edit the commit message for resulting commit. Since these commits are already in the remote repo, you will have to rewrite history by push --force as above.

Good luck! Let me know if you need more help.

**Comment by Poussinou** [comment]
ok I'll have look, thanks :)

**Pull request closed without merging**
