### PR TITLE
[WIP] First attempt to port to Godot 3.1

### PR DESCRIPTION
**Pull request by qarmin**
This is early port Tanks of Freedom to Godot 3.1

The game DOESN'T WORK for now.

I don't have much time, so maybe others people can end my work

What I done:
- [x] - Convert all scenes from xscn format to tscn
- [x] - Convert all resources from xml to tres
- [x] - Convert all indentations in scripts from spaces to tabs
- [x] - Convert game to Godot 3.0 with tool from Godot 2.1.5

What need to be done:
- [ ] - Restore .md and other missing files
- [ ] - Fix scripts
- [ ] - Fix other bugs

### CODE REVIEW

**Comment by czlowiekimadlo** [comment]
Hi quarmin, thank you for your contribution! I'm thinking on how to approach this. Probably creating a new branch for 3.1 is in order, I would like to merge to master only when we have a stable version.

**Comment by moisesguimaraes** [comment]
any updates here? I'm interested in learning Godot and I have 3.1 installed.

**Comment by czlowiekimadlo** [comment]
Hello @moisesguimaraes sorry for the delay, we do not actively develop ToF anymore. I have created a separate branch `godot3` for this porting effort, please push your code there. Also, please make a PR without .md files removal, as these are quite important.

**Comment by moisesguimaraes** [comment]
I was looking for that branch early yesterday 🤔

Is @qarmin still interested to push this forward?

**Comment by czlowiekimadlo** [comment]
I just added it, it wasn't here yesterday.

**Pull request closed without merging**
