### PR TITLE
Create translations_de.csv

### PR DESCRIPTION
**Pull request by Haretuerk**
New german translation.

### CODE REVIEW

**Comment by czlowiekimadlo** [comment]
Thank you for the contribution!

There are two separate translation files, that need to be included in order for a language to show up in game though. If possible, please also provide 'translations/campaigns/campaign_de.csv'. If you wish to skip it, just copy over the en file and push it like that, so the language will be functional, and may be improved later on.

**Comment by w84death** [comment]
I think that's our problem that we have two separate files. Contributors are confused. 
I will duplicate the campaign file just to include this one.

**Comment by Poussinou** [comment]
Yes this is very confusing, I'm not surprised the German contributor didn't translate the second file... You can't work with only one file?

**Comment by czlowiekimadlo** [comment]
I guess we could make it one, bigger file.

Wermooz made it like that, so we just went with it. Though, if we intend to make campaigns modular and allow for adding more, having a translation file per campaign might turn out better. I think we can get back to this with the team after Poznań Game Arena event and discuss.

**Comment by Poussinou** [comment]
OK;)

**Comment by Haretuerk** [comment]
Yes, I saw the campaign files and will do a german translation for it. No problem. Didn't have the time for it.
Campaigns as modules is a good idea, so please keep it separate.
Do missing campaign translation files cause an error or is the english file used as a fallback?

**Comment by czlowiekimadlo** [comment]
Without all the files the compacting process will fail. It is not a big deal though, as we haven't integrated the DE language yet - we are busy this weekend with PGA Expo. You are free to send the other translation file as another PR. Once we have a bit of time we will integrate the new langauge, and we will add missing files if needed.

**Comment by czlowiekimadlo** [comment]
Hey! I have finally found time to try and integrate German language into the game.

We have a limit of 20 characters per LABEL_\* key to limit text overflow in the interface. This limit does not apply to keys with different prefixes. We have expected to have some issues with German language, which tends to have long words ;)

Here is a list of labels, that are too long at the moment:
LABEL_WORKSHOP_FAILURE
LABEL_AUTO_FOLLOW
LABEL_MISSION_COMPLETED
LABEL_PREVIOUS_UNIT
LABEL_NEXT_UNIT

Do you think it is possible to make them shorter?
Also, we had to rename file to x_translations_de.csv so it is not being used until it passes validation. I have added a lot of new keys to this file linked to the new Online menu.

**Pull request merged**
