### PR TITLE
Create Переводbl

### PR DESCRIPTION
**Pull request by thesisek**
Sorry for another file

### CODE REVIEW

**Comment by thesisek** [comment]
Check it and say if it works good

**Comment by czlowiekimadlo** [comment]
Aside from, apparently, weird file name, it seems ok. I will test those commits later today and see if integration goes smoothly.

**Comment by thesisek** [comment]
Ok

**Comment by thesisek** [comment]
Aaand?

**Comment by czlowiekimadlo** [comment]
Still working on it ;) Not that much time to work on this side project since new Zelda game happened :D

**Comment by thesisek** [comment]
I put updated version (upper). An old one has lots of mistakws

**Comment by Potravni** [comment]
What's the news?

**Comment by czlowiekimadlo** [comment]
I had little trouble with some bug in the engine, but managed to integrate the RU language. You can see the result by running latest master version with the Godot editor. Many labels are way too long, but overall it is functional.

**Comment by thesisek** [comment]
Ок, аnd when it will be at game?

**Comment by czlowiekimadlo** [comment]
We are working on a major release, and we don't have any specific deadlines, so it may take a while.

**Pull request merged**
